export interface Book {
  id: string;
  title: string;
  author: string;
  description: string;
  tags: string[];
  slug: string;
  year?: string;
  featured?: boolean;
}

// Books I've read and reviewed
export const books: Book[] = [
  {
    id: 'the-language-game',
    title: 'The Language Game',
    author: 'Morten H. Christiansen, Nick Chater',
    description: 'How language isn\'t a set of rules but an improvisational game of charades we all play together.',
    tags: ['linguistics', 'cognition', 'communication'],
    slug: 'the-language-game',
    year: '2024',
    featured: true,
  },
  {
    id: 'titan',
    title: 'Titan: The Life of John D. Rockefeller Sr.',
    author: 'Ron Chernow',
    description: 'The definitive biography of America\'s first billionaire who reshaped business and philanthropy.',
    tags: ['biography', 'business', 'history', 'philanthropy'],
    slug: 'titan-the-life-of-john-d-rockefeller',
    year: '2024',
    featured: true,
  },
  {
    id: 'deng-xiaoping',
    title: 'Deng Xiaoping and the Transformation of China',
    author: 'Ezra Vogel',
    description: 'The colossus of 20th century who transformed China into a world power through pragmatic reforms.',
    tags: ['biography', 'china', 'politics', 'history'],
    slug: 'deng-xiaoping-and-the-transformation-of-china',
    year: '2024',
    featured: true,
  },
  {
    id: 'gandhi',
    title: 'Gandhi: The Years That Changed the World 1914-1948',
    author: 'Ramachandra Guha',
    description: 'A magnificent biography capturing both the saint and the human being filled with complexities and contradictions.',
    tags: ['biography', 'india', 'history', 'politics'],
    slug: 'gandhi-the-years-that-changed-the-world',
    year: '2024',
    featured: true,
  },
  {
    id: 'and-there-was-light',
    title: 'And There Was Light',
    author: 'Jon Meacham',
    description: 'One of the finest Lincoln biographies focusing on his evolving views towards slavery and moral struggles.',
    tags: ['biography', 'lincoln', 'american-history', 'slavery'],
    slug: 'and-there-was-light',
    year: '2024',
    featured: true,
  },
  {
    id: 'victorian-internet',
    title: 'The Victorian Internet',
    author: 'Tom Standage',
    description: 'How the telegraph revolutionized 19th century communication with uncanny parallels to our modern internet age.',
    tags: ['history', 'technology', 'communication'],
    slug: 'victorian-internet',
    year: '2024',
    featured: true,
  },
  {
    id: 'brunelleschis-dome',
    title: 'Brunelleschi\'s Dome',
    author: 'Ross King',
    description: 'How Filippo Brunelleschi built the impossible—a massive dome over Florence\'s cathedral without scaffolding.',
    tags: ['architecture', 'engineering', 'renaissance'],
    slug: 'brunelleschis-dome',
    year: '2024',
    featured: true,
  },
  {
    id: 'the-wright-brothers',
    title: 'The Wright Brothers',
    author: 'David McCullough',
    description: 'Two bicycle mechanics from Dayton, Ohio changed what humans could do through grit and patient experimentation.',
    tags: ['aviation', 'innovation', 'biography'],
    slug: 'the-wright-brothers',
    year: '2024',
    featured: true,
  },
  {
    id: 'the-path-between-the-seas',
    title: 'The Path Between the Seas',
    author: 'David McCullough',
    description: 'The epic story of building the Panama Canal—cutting a continent in half and connecting two oceans.',
    tags: ['engineering', 'history', 'infrastructure'],
    slug: 'the-path-between-the-seas',
    year: '2024',
    featured: true,
  },
  {
    id: 'how-doctors-think',
    title: 'How Doctors Think',
    author: 'Jerome Groopman',
    description: 'A field guide to medical thinking—how doctors make decisions, where they go wrong, and how patients can help.',
    tags: ['medicine', 'cognition', 'healthcare'],
    slug: 'how-doctors-think',
    year: '2024',
    featured: true,
  },
  {
    id: 'golden-road',
    title: 'The Golden Road',
    author: 'William Dalrymple',
    description: 'A love letter to Indian civilization showing how India exported its ideas across half the world.',
    tags: ['india', 'history', 'culture', 'trade'],
    slug: 'the-golden-road',
    year: '2024',
    featured: true,
  },
  {
    id: 'frostbite',
    title: 'Frostbite',
    author: 'Nicola Twilley',
    description: 'An ambitious journey exploring the hidden world of refrigeration that quietly remade modern life.',
    tags: ['technology', 'food', 'history', 'infrastructure'],
    slug: 'frostbite',
    year: '2024',
    featured: true,
  },
  {
    id: 'abundance',
    title: 'Abundance',
    author: 'Ezra Klein, Derek Thompson',
    description: 'A manifesto for supply-side liberalism arguing liberals should focus on building more, not just redistribution.',
    tags: ['politics', 'economics', 'policy', 'housing'],
    slug: 'abundance',
    year: '2024',
    featured: true,
  },
  {
    id: 'empress-of-the-nile',
    title: 'Empress of the Nile',
    author: 'Lynne Olson',
    description: 'The story of Christiane Desroches-Noblecourt who rallied the world to save Abu Simbel from drowning.',
    tags: ['biography', 'egypt', 'archaeology', 'history'],
    slug: 'empress-of-the-nile',
    year: '2024',
    featured: true,
  },
  {
    id: 'notre-dame',
    title: 'Notre-Dame: the Soul of France',
    author: 'Agnes Poirier',
    description: 'The cathedral\'s 850-year journey through French history and the heroic effort to save it from the 2019 fire.',
    tags: ['france', 'architecture', 'history', 'notre-dame'],
    slug: 'notre-dame-soul-of-france',
    year: '2024',
  },
  {
    id: 'chasing-the-monsoon',
    title: 'Chasing the Monsoon',
    author: 'Alexander Frater',
    description: 'Following India\'s unpredictable life-giving rains from Kerala to Cherrapunji.',
    tags: ['india', 'monsoon', 'travel', 'culture'],
    slug: 'chasing-the-monsoon',
    year: '2024',
  },
  {
    id: 'the-mosquito',
    title: 'The Mosquito',
    author: 'Timothy Winegard',
    description: 'How a tiny insect shaped human history more than any other animal.',
    tags: ['history', 'disease', 'biology'],
    slug: 'the-mosquito',
    year: '2024',
  },
  {
    id: 'beyond-measure',
    title: 'Beyond Measure',
    author: 'James Vincent',
    description: 'The hidden history of measurement from Egyptian Nilometers to the metric system.',
    tags: ['measurement', 'history', 'science'],
    slug: 'beyond-measure',
    year: '2024',
  },
  {
    id: 'the-swerve',
    title: 'The Swerve',
    author: 'Stephen Greenblatt',
    description: 'How a 15th century book hunter\'s discovery helped ignite the Renaissance.',
    tags: ['history', 'renaissance', 'philosophy'],
    slug: 'the-swerve',
    year: '2024',
  },
  {
    id: 'kingdom-of-characters',
    title: 'Kingdom of Characters',
    author: 'Jing Tsu',
    description: 'How Chinese script evolved through centuries of technological challenges.',
    tags: ['china', 'language', 'technology', 'linguistics'],
    slug: 'kingdom-of-characters',
    year: '2024',
  },
  {
    id: 'cod',
    title: 'Cod',
    author: 'Mark Kurlansky',
    description: 'How a simple fish shaped Viking explorations, colonial trade, and American independence.',
    tags: ['history', 'food', 'trade'],
    slug: 'cod-fish-that-changed-history',
    year: '2024',
  },
  {
    id: 'rivers-of-powers',
    title: 'Rivers of Powers',
    author: 'Laurence C. Smith',
    description: 'A delightful take on rivers combining history, geography, environmentalism, and urban planning.',
    tags: ['rivers', 'geography', 'environment', 'history'],
    slug: 'rivers-of-powers',
    year: '2024',
  },
  {
    id: 'knife',
    title: 'Knife',
    author: 'Salman Rushdie',
    description: 'Rushdie meditates on the knife attack, his recovery, and the broader question of free speech.',
    tags: ['memoir', 'free-speech', 'literature'],
    slug: 'knife-by-salman-rushdie',
    year: '2024',
  },
  {
    id: 'kamal-haasan',
    title: 'Kamal Haasan',
    author: 'K. Hariharan',
    description: 'A love letter to 40 of Kamal Haasan\'s best movies with interviews and behind-the-scenes stories.',
    tags: ['cinema', 'tamil', 'biography', 'india'],
    slug: 'kamal-haasan-by-k-hariharan',
    year: '2024',
  },
  {
    id: 'hardest-job',
    title: 'The Hardest Job in the World',
    author: 'John Dickerson',
    description: 'A primer on presidential leadership peppered with quotes, anecdotes, and insights.',
    tags: ['presidency', 'american-politics', 'leadership'],
    slug: 'the-hardest-job-in-the-world',
    year: '2024',
  },
  {
    id: 'where-water-goes',
    title: 'Where the Water Goes',
    author: 'David Owen',
    description: 'The fascinating story of Colorado River\'s water rights and management.',
    tags: ['water', 'environment', 'colorado', 'america'],
    slug: 'where-the-water-goes',
    year: '2024',
  },
  {
    id: 'three-languages',
    title: 'Three Languages of Politics',
    author: 'Arnold Kling',
    description: 'A quick primer on progressive, conservative, and libertarian political languages.',
    tags: ['politics', 'political-theory'],
    slug: 'three-languages-of-politics',
    year: '2024',
  },
  {
    id: 'there-will-be-fire',
    title: 'There Will Be Fire',
    author: 'Rory Carroll',
    description: 'The investigation of the 1984 Brighton hotel bombing assassination attempt on Margaret Thatcher.',
    tags: ['history', 'ireland', 'terrorism', 'thatcher'],
    slug: 'there-will-be-fire',
    year: '2024',
  },
  {
    id: 'domestic-revolution',
    title: 'The Domestic Revolution',
    author: 'Ruth Goodman',
    description: 'How England switched from wood to coal and transformed kitchens and domestic work.',
    tags: ['history', 'energy', 'domestic-life', 'england'],
    slug: 'the-domestic-revolution',
    year: '2024',
  },
  {
    id: 'against-the-gods',
    title: 'Against The Gods',
    author: 'Peter L. Bernstein',
    description: 'The remarkable story of risk and how humans learned to tame uncertainty.',
    tags: ['risk', 'probability', 'history', 'finance'],
    slug: 'against-the-gods',
    year: '2024',
  },
  {
    id: 'reluctant-darwin',
    title: 'The Reluctant Mr. Darwin',
    author: 'David Quammen',
    description: 'Darwin\'s procrastination in publishing Origin of Species and his varied experiments.',
    tags: ['biography', 'darwin', 'evolution', 'science'],
    slug: 'reluctant-mr-darwin',
    year: '2024',
  },
  {
    id: 'vajpayee',
    title: 'Atal Bihari Vajpayee: A Man for All Seasons',
    author: 'Kingshuk Nag',
    description: 'Biography of one of India\'s most respected prime ministers.',
    tags: ['biography', 'india', 'politics'],
    slug: 'atal-bihari-vajpayee',
    year: '2024',
  },
  {
    id: 'the-source',
    title: 'The Source',
    author: 'Martin Doyle',
    description: 'How America\'s rivers and streams made America and then America remade them.',
    tags: ['rivers', 'america', 'infrastructure', 'history'],
    slug: 'the-source',
    year: '2024',
  },
  {
    id: 'against-the-grain',
    title: 'Against the Grain',
    author: 'James C. Scott',
    description: 'The interregnum between when agriculture started and states established themselves.',
    tags: ['agriculture', 'civilization', 'anthropology'],
    slug: 'against-the-grain',
    year: '2024',
  },
  {
    id: 'troublesome-young-men',
    title: 'Troublesome Young Men',
    author: 'Lynne Olson',
    description: 'The palace intrigue that ousted Chamberlain and brought Churchill to power.',
    tags: ['history', 'britain', 'world-war-2', 'churchill'],
    slug: 'troublesome-young-men',
    year: '2024',
  },
  {
    id: 'madisons-gift',
    title: 'Madison\'s Gift',
    author: 'David O. Stewart',
    description: 'How James Madison collaborated with Hamilton, Washington, Jefferson, and his wife Dolley.',
    tags: ['biography', 'american-history', 'constitution'],
    slug: 'madisons-gift',
    year: '2024',
  },
  {
    id: 'supreme-court',
    title: 'The Supreme Court',
    author: 'William Rehnquist',
    description: 'Chief Justice Rehnquist\'s readable history of the Supreme Court\'s milestones.',
    tags: ['law', 'supreme-court', 'american-history'],
    slug: 'the-supreme-court',
    year: '2024',
  },
  {
    id: 'ascent-of-money',
    title: 'The Ascent of Money',
    author: 'Niall Ferguson',
    description: 'The financial history of the world through banking, bonds, stocks, and more.',
    tags: ['finance', 'economics', 'history'],
    slug: 'the-ascent-of-money',
    year: '2024',
  },
  {
    id: 'anaximander',
    title: 'Anaximander',
    author: 'Carlo Rovelli',
    description: 'The pre-Socratic philosopher who figured out Earth is a sphere floating in space.',
    tags: ['philosophy', 'science', 'ancient-greece'],
    slug: 'anaximander',
    year: '2024',
  },
  {
    id: 'men-machines',
    title: 'Men, Machines and Modern Times',
    author: 'Elting E. Morison',
    description: 'A must-read on generational transformation and technological change.',
    tags: ['technology', 'history', 'innovation'],
    slug: 'men-machines-and-modern-times',
    year: '2024',
  },
  {
    id: 'midnight-siberia',
    title: 'Midnight in Siberia',
    author: 'David Greene',
    description: 'An NPR reporter\'s trans-siberian train journey exploring Russian democracy.',
    tags: ['russia', 'travel', 'politics'],
    slug: 'midnight-in-siberia',
    year: '2024',
  },
  {
    id: 'ruins-of-empire',
    title: 'From the Ruins of the Empire',
    author: 'Pankaj Mishra',
    description: 'Asian intellectuals\' responses to Western colonialism through Jamal al-Afghani, Liang Qichao, and Tagore.',
    tags: ['asia', 'colonialism', 'history', 'politics'],
    slug: 'from-the-ruins-of-the-empire',
    year: '2024',
  },
  {
    id: 'hindu-temples',
    title: 'All About Hindu Temples',
    author: 'Swami Harshananda',
    description: 'A guide to Hindu temple architecture, rituals, and religious significance.',
    tags: ['hinduism', 'architecture', 'religion', 'india'],
    slug: 'all-about-hindu-temples',
    year: '2024',
  },
  {
    id: 'brief-history-intelligence',
    title: 'A Brief History of Intelligence',
    author: 'Max Bennett',
    description: 'Five key breakthroughs that shaped intelligence from simple worms to spaceships and poetry.',
    tags: ['neuroscience', 'evolution', 'intelligence', 'biology'],
    slug: 'a-brief-history-of-intelligence',
    year: '2024',
  },
  {
    id: 'byomkesh',
    title: 'Byomkesh Bakshi Stories',
    author: 'Saradindu Bandopadhyay',
    description: 'Six detective stories featuring the truth-seeker Byomkesh, though the translation is pedestrian.',
    tags: ['fiction', 'detective', 'bengal', 'india'],
    slug: 'byomkesh-bakshi-stories',
    year: '2024',
  },
  {
    id: 'india-moving',
    title: 'India Moving: A History of Migration',
    author: 'Chinmay Tumbe',
    description: 'Anecdotes and stories about migration within and away from India.',
    tags: ['india', 'migration', 'history', 'demographics'],
    slug: 'india-moving-a-history-of-migration',
    year: '2024',
  },
  {
    id: 'world-made-west',
    title: 'How the World Made the West',
    author: 'Josephine Quinn',
    description: 'Challenging the notion of pure Western civilization by showing global interconnections.',
    tags: ['history', 'civilization', 'culture'],
    slug: 'how-the-world-made-the-west',
    year: '2024',
  },
  {
    id: 'culture-story',
    title: 'Culture: The Story of Us, from Cave Art to K-Pop',
    author: 'Martin Puchner',
    description: 'A tour of how culture gets made, preserved, and passed down through history.',
    tags: ['culture', 'history', 'anthropology'],
    slug: 'culture-the-story-of-us',
    year: '2024',
  },
  {
    id: 'unthinkable',
    title: 'Unthinkable',
    author: 'Helen Thomson',
    description: 'Nine case studies of maverick brains explaining normal brain function.',
    tags: ['neuroscience', 'psychology', 'brain'],
    slug: 'unthinkable',
    year: '2024',
  },
  {
    id: 'chile-project',
    title: 'The Chile Project',
    author: 'Sebastian Edwards',
    description: 'How Chile became the testing ground for free-market economics with lasting consequences.',
    tags: ['economics', 'chile', 'politics', 'history'],
    slug: 'the-chile-project',
    year: '2024',
  },
  {
    id: 'fever-heartland',
    title: 'A Fever in the Heartland',
    author: 'Timothy Egan',
    description: 'The chilling story of the Ku Klux Klan\'s rise to power in 1920s Indiana.',
    tags: ['history', 'america', 'racism', 'kkk'],
    slug: 'a-fever-in-the-heartland',
    year: '2024',
  },
  {
    id: 'the-negotiator',
    title: 'The Negotiator',
    author: 'George Mitchell',
    description: 'Memoir of the senator who helped broker the Good Friday Agreement in Northern Ireland.',
    tags: ['biography', 'politics', 'northern-ireland', 'negotiation'],
    slug: 'the-negotiator',
    year: '2024',
  },
  {
    id: 'our-moon',
    title: 'Our Moon',
    author: 'Rebecca Boyle',
    description: 'A poetic journey into how the Moon shaped our minds and continues to influence Earth.',
    tags: ['moon', 'astronomy', 'science', 'history'],
    slug: 'our-moon',
    year: '2024',
  },
  {
    id: 'vagbhushanam',
    title: 'vāgbhūṣaṇaṁ bhūṣaṇaṁ',
    author: 'Iriventi Krishnamurthy',
    description: 'A Telugu booklet on becoming a good public speaker drawing from various sources.',
    tags: ['telugu', 'public-speaking', 'communication'],
    slug: 'vagbhushanam-bhushanam',
    year: '2024',
  },
  {
    id: 'conclave',
    title: 'Conclave',
    author: 'Robert Harris (Movie: 2024)',
    description: 'A thriller exploring papal election and the question of power and those who seek it.',
    tags: ['movie', 'vatican', 'power', 'politics'],
    slug: 'conclave',
    year: '2024',
  },
  {
    id: 'sing-dance-pray',
    title: 'Sing, Dance and Pray',
    author: 'Hindol Sengupta',
    description: 'The story of A.C. Bhaktivedanta Swami and how ISKCON took root in the West.',
    tags: ['biography', 'religion', 'hinduism', 'krishna', 'iskcon'],
    slug: 'sing-dance-and-pray',
    year: '2024',
  },
  {
    id: 'airless-wilds',
    title: 'Across the Airless Wilds',
    author: 'Earl Swift',
    description: 'The incredible story of the Lunar Rover and the final three Apollo moon missions.',
    tags: ['space', 'moon', 'engineering', 'apollo'],
    slug: 'across-the-airless-wilds',
    year: '2024',
  },
  {
    id: 'age-of-wood',
    title: 'The Age of Wood',
    author: 'Roland Ennos',
    description: 'How human civilization owes more to wood than to stone, metal, or fire.',
    tags: ['wood', 'history', 'materials', 'civilization'],
    slug: 'the-age-of-wood',
    year: '2024',
  },
  {
    id: 'cross-purposes',
    title: 'Cross Purposes: Christianity\'s Broken Bargain with Democracy',
    author: 'Jonathan Rauch',
    description: 'How American religious life\'s decline affects democracy and civic virtue.',
    tags: ['religion', 'democracy', 'politics', 'christianity'],
    slug: 'cross-purposes-christianitys-broken-bargain',
    year: '2024',
  },
  {
    id: 'pine-barrens',
    title: 'The Pine Barrens',
    author: 'John McPhee',
    description: 'A portrait of New Jersey\'s Pine Barrens and the massive aquifer beneath.',
    tags: ['nature', 'environment', 'new-jersey', 'water'],
    slug: 'the-pine-barrens',
    year: '2024',
  },
  {
    id: 'ninety-days',
    title: 'Ninety Days: The Hunt for Rajiv Gandhi\'s Assassins',
    author: 'Anirudhya Mitra',
    description: 'The fast-paced manhunt following Rajiv Gandhi\'s 1991 assassination.',
    tags: ['india', 'history', 'assassination', 'investigation'],
    slug: 'ninety-days-hunt-for-rajiv-gandhis-assassins',
    year: '2024',
  },
  {
    id: 'sixteen-stormy-days',
    title: 'Sixteen Stormy Days',
    author: 'Tripurdaman Singh',
    description: 'India\'s First Amendment that curtailed free speech, property rights, and enabled reservations.',
    tags: ['india', 'constitution', 'law', 'history'],
    slug: 'sixteen-stormy-days',
    year: '2024',
  },
  {
    id: 'if-i-understood-you',
    title: 'If I Understood You, Would I Have This Look on My Face?',
    author: 'Alan Alda',
    description: 'A guide to better communication combining improv, science, and storytelling.',
    tags: ['communication', 'science', 'empathy'],
    slug: 'if-i-understood-you',
    year: '2024',
  },
  {
    id: 'old-ways',
    title: 'The Old Ways',
    author: 'Robert Macfarlane',
    description: 'Ancient footpaths and their layers of meaning connecting walking with knowing.',
    tags: ['walking', 'nature', 'philosophy', 'paths'],
    slug: 'the-old-ways',
    year: '2024',
  },
  {
    id: 'river-of-doubt',
    title: 'The River of Doubt',
    author: 'Candice Millard',
    description: 'Theodore Roosevelt\'s harrowing Amazon expedition that nearly killed him.',
    tags: ['biography', 'roosevelt', 'amazon', 'adventure'],
    slug: 'the-river-of-doubt',
    year: '2024',
  },
  {
    id: 'british-in-india',
    title: 'The British in India: A Social History of the Raj',
    author: 'David Gilmour',
    description: 'A social history of the men and women who lived and died in British India.',
    tags: ['india', 'british-raj', 'history', 'colonialism'],
    slug: 'the-british-in-india',
    year: '2024',
  },
  {
    id: 'mathematica',
    title: 'Mathematica',
    author: 'David Bessis',
    description: 'Mathematics as an act of seeing—building intuition rather than memorizing.',
    tags: ['mathematics', 'education', 'intuition', 'learning'],
    slug: 'mathematica',
    year: '2024',
  },
  {
    id: 'parcels-beijing',
    title: 'I Deliver Parcels in Beijing',
    author: 'Hu Anyan',
    description: 'A memoir of gig-worker precarity in China\'s delivery economy.',
    tags: ['china', 'labor', 'memoir', 'economics'],
    slug: 'i-deliver-parcels-in-beijing',
    year: '2024',
  },
  {
    id: 'hitlers-people',
    title: 'Hitler\'s People',
    author: 'Richard Evans',
    description: 'How ordinary Germans became complicit in the Holocaust—teachers, artists, bureaucrats who gradually suspended judgment and redefined virtue in the image of power.',
    tags: ['history', 'world-war-2', 'germany', 'holocaust', 'biography'],
    slug: 'hitlers-people',
    year: '2024',
    featured: true,
  },
  {
    id: 'michelangelo-popes-ceiling',
    title: 'Michelangelo and the Pope\'s Ceiling',
    author: 'Ross King',
    description: 'How a sculptor who hated painting created the Sistine Chapel ceiling—mastering perspective, chemistry, and sublime art under Pope Julius II.',
    tags: ['art', 'renaissance', 'michelangelo', 'vatican', 'biography'],
    slug: 'michelangelo-and-the-popes-ceiling',
    year: '2024',
    featured: true,
  },
];

export function getAllBooks(): Book[] {
  return books;
}

export function getFeaturedBooks(): Book[] {
  return books.filter((book) => book.featured);
}

export function getBookById(id: string): Book | undefined {
  return books.find((book) => book.id === id);
}

export function getBooksByTag(tag: string): Book[] {
  return books.filter((book) => book.tags.includes(tag));
}

export function getAllBookTags(): string[] {
  const tags = new Set<string>();
  books.forEach((book) => {
    book.tags.forEach((tag) => tags.add(tag));
  });
  return Array.from(tags).sort();
}
